### ISSUE TITLE
Add tags view on channel cell

### ISSUE THREAD

**Issue by laqiguy** [LetItPlay/iOSClient#7]
Every channel can have multiple tags. 4 (or less) of them should be presented on its cell.

Not clickable.
Without size sorting. 
Just tags.

<img width="379" alt="screen shot 2017-11-08 at 14 29 49" src="https://user-images.githubusercontent.com/3822383/32541378-5a8b2902-c491-11e7-80a6-b96a0c16ad48.png">

**Comment by Danilgubaydulin** [comment]
Channel screen scrolling lags. Please, fix it
